/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package logikcull.loadfiles

import com.nhaarman.mockitokotlin2.any
import com.nhaarman.mockitokotlin2.doReturn
import com.nhaarman.mockitokotlin2.mock
import logikcull.loadfiles.parser.OptLoadFileParser
import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test
    fun optSuccessfulParse() {
        val fullPath = javaClass.getResource("/test.opt").path

        val parserFactory = mock<ParserFactory> {
            on { getParser(any()) } doReturn OptLoadFileParser(fullPath)
        }
        val subject = App(parserFactory)
        val opt = subject.parse(javaClass.getResource("/test.opt").path)
        assertEquals(opt.parse().size, 3)
    }
}
